### ISSUE TITLE
bounding box cuts off nodes

### ISSUE THREAD

**Issue by SimonEnsemble** [MakieOrg/GraphMakie.jl#173] opened 2024-02-25 18:25 UTC
the automatic determination of x- and y-lims tends to cut off my (big) nodes.

would be nice if there were a `padding` feature to add padding to the x- and y-lims to expand the bounding box.
(I'm making many such figures so manual tuning of axes not acceptable.)

oddly I get the following values for the automatically determined x, y-axis limits (which I seek to modify) for this plot. the y-axis limits are clearly incorrect.
```
ax.yaxis.attributes.limits[] = (0.0f0, 10.0f0)
ax.xaxis.attributes.limits[] = (0.0f0, 10.0f0)
```

<img width="251" alt="Screenshot 2024-02-25 at 10 15 34 AM" src="https://github.com/MakieOrg/GraphMakie.jl/assets/30643894/4efda87d-96e0-41e9-9057-41c217810abe">

another posting a similar issue [here](https://stackoverflow.com/questions/75175076/graphmakie-jl-cuts-off-text).

**Comment by SimonEnsemble** [comment] 2024-02-25 18:38
so bizarre. the yaxis limits are not being retrieved inside the function. but outside the function they are.

<img width="730" alt="Screenshot 2024-02-25 at 10 38 08 AM" src="https://github.com/MakieOrg/GraphMakie.jl/assets/30643894/ebf6801d-a2ba-4d77-8163-2abef0f3d047">

**Comment by asinghvi17** [comment] 2024-02-25 19:50
As to the last post, final limits are always computed at display time.  You can run `Makie.update_state_before_display!(fig)` to make them compute limits, though.

**Comment by hexaeder** [comment] 2024-02-25 20:16
I'll close this issue as a duplicate of #141.

I think the underlying issue is that the Makie limit calculation does not take things into account that are drawn in pixel space rather than data space, i.e., elements that are displayed at the same size regardless of zoom level. Calculating proper limits is nontrivial since the limits affect the zoom level and, therefore, the projection of the pixel-space objects into data space.

[This discourse post](https://discourse.julialang.org/t/textbox-graph-with-networklayout-with-labels-cut-off-using-graphmakie/96566/4) might help you to define a function to fix the limits after plotting.

**Closed by hexaeder** 2024-02-25 20:16 UTC
