### ISSUE TITLE
Precompilation stuck on Julia 1.9

### ISSUE THREAD

**Issue by mofeing** [MakieOrg/GraphMakie.jl#130] opened 2023-05-07 10:27 UTC
I have a Package Extension on my [package](https://github.com/bsc-quantic/Tenet.jl) for visualization using GraphMakie, which we test on CI. Recently I've found out a strange behavior on Julia 1.9.0.rc3 (I think that it also happened in 1.9.0.rc2). Whenever we run the tests, the precompilation of the Package Extension gets stuck indefinitely.

[Link](https://github.com/bsc-quantic/Tenet.jl/actions/runs/4906315467/jobs/8760686555) to an example log (it doesn't appear but I've checked on local that it gets stuck on the Package Extension precompilation). The same tests run correctly on Julia v1.8.5.

I've narrowed down the problem and it looks like importing `GraphMakie` before `Makie` is the problem.

## Steps to reproduce

```
gh repo clone bsc-quantic/Tenet.jl

# failing commit
git checkout 481f486
julia --project -e "using Pkg; Pkg.test()"

# succesful commit
git checkout 85147d7
julia --project -e "using Pkg; Pkg.test()"
```

**Comment by hexaeder** [comment] 2023-05-08 08:59
I am not able to resolve the specific commits, are they pushed?
```
~/tmp/Tenet.jl master ❯ git checkout 481f486
error: pathspec '481f486' did not match any file(s) known to git
```
Therefore i wasn't able to reproduce the problem. If it spins forever in precompilation it might be also worth raising an issue to pkg directly...

However two comments about the `Project.tml` on master:
You have `GraphMakie` as a strong dependency but `Makie` as a weak dep. That won't work since `GraphMakie` itself depends on `Makie`. I guess you want something like
```
MakieExt = "Makie, GraphMakie"
```
instead (not sure though, havn't played around with PkgExtensions yet).

Also, completly unrelated, you declare compatiblity with upcomming breaking releases in `GraphMakie`
```
GraphMakie = ">=0.4,<1"
```
I'd strongly recommend to use `"0.4, 0.5"` and wait for CompatHelper to update them if ther's a new release and you checked that your recipes still work.

**Comment by mofeing** [comment] 2023-05-08 09:27
> I am not able to resolve the specific commits, are they pushed?

Yep, but they are not merged into `master`. Maybe you have to checkout to the `refactor/new-tn` branch first?

> However two comments about the `Project.tml` on master: You have `GraphMakie` as a strong dependency but `Makie` as a weak dep. That won't work since `GraphMakie` itself depends on `Makie`. I guess you want something like
> 
> ```
> MakieExt = "Makie, GraphMakie"
> ```
> 
> instead (not sure though, havn't played around with PkgExtensions yet).

This is fine, I spoke with people in charge of the Package Extensions on Slack. What I want is that whenever the `Makie` is loaded into the env, then load my extension. If I put both `Makie` and `GraphMakie`, then the user will need to load both (but I don't want the user to be aware of `GraphMakie`).

I need to put `GraphMakie` as a strong dependency in order to download it such that when it works when I do `using GraphMakie` in my extension (`weakdeps` do not fetch the package).

> I'd strongly recommend to use "0.4, 0.5" and wait for CompatHelper to update them if ther's a new release and you checked that your recipes still work.

Okay, I'll do that on `master`.

**Comment by hexaeder** [comment] 2023-05-10 11:44
I get different commit hashes on that branch but I saw the changes now. Still cannot reproduce because it seems to use an unregistered packages `Tensors` which is not the same as the [registered one](https://github.com/Ferrite-FEM/Tensors.jl)?

I still think this is kind of a weird cornercase in PkgExtensions and might be a bug, I don't know how it can be related to `GraphMakie`. In short:

Tennet.jl has GraphMakie as a strong dependency. Therefore it also has Makie as a strong dependency. Additonally, you define Makie as a weak dependency and tell Julia to load your extension whenever Makie is imported. Maybe the problem is that by writing `using GraphMakie` in your extension you implicitly call `using Makie` and that somehow triggers the extension again? I've seen you discussed that with @KristofferC on slack, I guess he'd know best.

Next step in debugging might be to create a minimal package with this kind of extension setup using other packages then GraphMakie/Makie and see if it still freezes depending on the `using` order in the extension module.

**Comment by KristofferC** [comment] 2023-05-10 11:54
I would also suggest trying things on julia master since it has better detection for loading problems and should give an error instead of getting stuck.

**Comment by mofeing** [comment] 2023-05-10 16:43
> I get different commit hashes on that branch but I saw the changes now. Still cannot reproduce because it seems to use an unregistered packages `Tensors` which is not the same as the [registered one](https://github.com/Ferrite-FEM/Tensors.jl)?

Sorry, I forgot to explain that I'm using our own [federated registry](https://github.com/bsc-quantic/Registry). So effectively, our [`Tensors`](https://github.com/bsc-quantic/Tensors.jl) is different from the registered in the General registry.

This should solve it.
```julia
]registry add https://github.com/bsc-quantic/Registry
```

> I still think this is kind of a weird cornercase in PkgExtensions and might be a bug, I don't know how it can be related to GraphMakie.

Yep, but this bug appeared probably between 1.9.0-rc2 and 1.9.0-rc3. I'm gonna check it anyway.

> Next step in debugging might be to create a minimal package with this kind of extension setup using other packages then GraphMakie/Makie and see if it still freezes depending on the using order in the extension module.

Okay, I'm on it.

**Comment by hexaeder** [comment] 2023-06-12 07:50
I'll close this here since I don't think this is something actionable for GraphMakie, seems to me like a Julia/pkg problem. Please feel free to reopen if you think otherwise :)

**Closed by hexaeder** 2023-06-12 07:50 UTC
