### ISSUE TITLE
Nodes get cut-off when ilabels_fontsize is set to large number.

### ISSUE THREAD

**Issue by newptcai** [MakieOrg/GraphMakie.jl#196] opened 2024-11-18 14:44 UTC
I have the following code to draw a directed graph with edge weights.

```
## Load the packages
using Random
using CairoMakie
using GraphMakie
using Graphs
using LaTeXStrings
using Colors

## Create a random directed graph
vnum = 4
enum = 6
ilabels = string.('a':'z')[1:vnum]
seed = 1234
g = erdos_renyi(4, 6, is_directed = true, seed = seed)
Random.seed!(seed)
elabels = LaTeXString.(string.(rand(1:10, enum)))

## Plot the data
font_size = 32
fig, ax, p = graphplot(
    g;
    ilabels = ilabels,
    ilabels_fontsize = font_size,
    elabels = elabels,
    elabels_fontsize = font_size,
    node_color = :orange,
    edge_color = :gray,
    edge_width = 4,
    node_strokewidth = 4,
    arrow_shift = :end,
    arrow_size = 40,
);
hidedecorations!(ax);
hidespines!(ax);
colsize!(fig.layout, 1, Aspect(1, 1.0));
resize_to_layout!(fig);
fig
```

![Image](https://github.com/user-attachments/assets/c6011f3d-5d04-4d80-bd61-7ca490e03956)

As you can see, the nodes in the picture gets cut off when they are too large. Is there any way to avoid this?

**Comment by hexaeder** [comment] 2024-11-18 18:26
I'll close this as a duplicate of #141. 

Peviously I posted some code on discourse to work around that problem: https://discourse.julialang.org/t/textbox-graph-with-networklayout-with-labels-cut-off-using-graphmakie/96566/3

Unfortunately, I still don't know how to solve this fundamentally. The problem is, that this would be an iterative process since the nodes are drawn in pixelspace. Therefore, its hard to predict where the axis limits need to be exactly (axis limits change pixel/per_data_unit scale which changes the axis limits and so on.

**Closed by hexaeder** 2024-11-18 18:26 UTC
