### ISSUE TITLE
segfault on readme example 

### ISSUE THREAD

**Issue by anandijain** [MakieOrg/GraphMakie.jl#110] opened 2023-01-29 16:51 UTC
mwe:
  ```julia
using GLMakie
using GraphMakie
using Graphs
g = complete_graph(10)
graphplot(g)
  ```
  trace:
  ```
  [3144] signal (11.2): Segmentation fault: 11
in expression starting at none:0
_ZN9libunwind10CFI_ParserINS_17LocalAddressSpaceEE9decodeFDEERS1_mPNS2_8FDE_InfoEPNS2_8CIE_InfoE at /usr/lib/system/libunwind.dylib (unknown line)
Allocations: 46273614 (Pool: 46267756; Big: 5858); GC: 61
fish: Job 1, 'julia --startup-file=no $argv' terminated by signal SIGSEGV (Address boundary error)
  ```

  versioninfo():
  ```julia
  Julia Version 1.9.0-beta3
Commit 24204a73447 (2023-01-18 07:20 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 8 on 4 virtual cores
Environment:
  JULIA_NUM_THREADS = 8


  ```
  <details>
  <summary>Manifest</summary>
  
  ```julia
  Status `~/.julia/environments/graphmakie/Manifest.toml`
  [621f4979] AbstractFFTs v1.2.1
  [1520ce14] AbstractTrees v0.4.4
  [79e6a3ab] Adapt v3.5.0
  [27a7e980] Animations v0.4.1
  [ec485272] ArnoldiMethod v0.2.0
  [67c07d97] Automa v0.8.2
  [13072b0f] AxisAlgorithms v1.0.1
  [39de3d68] AxisArrays v0.4.6
  [fa961155] CEnum v0.4.2
  [49dc2e85] Calculus v0.5.1
  [d360d2e6] ChainRulesCore v1.15.7
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.20.0
  [3da002f7] ColorTypes v0.11.4
  [c3611d14] ColorVectorSpace v0.9.10
  [5ae59095] Colors v0.12.10
  [34da2185] Compat v4.5.0
  [187b0558] ConstructionBase v1.4.1
  [d38c429a] Contour v0.6.2
  [9a962f9c] DataAPI v1.14.0
  [864edb3b] DataStructures v0.18.13
  [e2d170a0] DataValueInterfaces v1.0.0
  [b429d917] DensityInterface v0.4.0
  [31c24e10] Distributions v0.25.80
  [ffbed154] DocStringExtensions v0.9.3
  [fa6b7ba4] DualNumbers v0.6.8
  [411431e0] Extents v0.1.1
  [c87230d0] FFMPEG v0.4.1
  [7a1cc6ca] FFTW v1.5.0
  [5789e2e9] FileIO v1.16.0
  [1a297f60] FillArrays v0.13.7
  [53c48c17] FixedPointNumbers v0.8.4
  [59287772] Formatting v0.4.2
  [b38be410] FreeType v4.0.0
  [663a7486] FreeTypeAbstraction v0.10.0
  [f7f18e0c] GLFW v3.4.1
  [e9467ef8] GLMakie v0.8.1
  [46192b85] GPUArraysCore v0.1.3
  [cf35fbd7] GeoInterface v1.2.1
  [5c1252a2] GeometryBasics v0.4.5
  [1ecd5474] GraphMakie v0.5.2
  [a2bd30eb] Graphics v1.1.2
  [86223c79] Graphs v1.7.4
  [3955a311] GridLayoutBase v0.9.1
  [42e2da0e] Grisu v1.0.2
  [34004b35] HypergeometricFunctions v0.3.11
  [2803e5a7] ImageAxes v0.6.10
  [c817782e] ImageBase v0.1.5
  [a09fc81d] ImageCore v0.9.4
  [82e4d734] ImageIO v0.6.6
  [bc367c6b] ImageMetadata v0.9.8
  [9b13fd28] IndirectArrays v1.0.0
  [d25df0c9] Inflate v0.1.3
  [a98d9a8b] Interpolations v0.14.7
  [8197267c] IntervalSets v0.7.4
  [3587e190] InverseFunctions v0.1.8
  [92d709cd] IrrationalConstants v0.1.1
  [f1662d9f] Isoband v0.1.1
  [c8e1da08] IterTools v1.4.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.4.1
  [682c06a0] JSON v0.21.3
  [b835a17e] JpegTurbo v0.1.1
  [5ab0869b] KernelDensity v0.6.5
  [b964fa9f] LaTeXStrings v1.3.0
  [8cdb02fc] LazyModules v0.3.1
  [2ab3a3ac] LogExpFunctions v0.3.20
  [1914dd2f] MacroTools v0.5.10
⌅ [ee78f7c6] Makie v0.19.1
⌅ [20f20a25] MakieCore v0.6.1
  [dbb5928d] MappedArrays v0.4.1
  [7eb4fadd] Match v1.2.0
  [0a4f8689] MathTeXEngine v0.5.4
  [7269a6da] MeshIO v0.4.10
  [978d7f02] MiniQhull v0.4.0
  [e1d29d7a] Missings v1.1.0
  [66fc600b] ModernGL v1.1.6
  [e94cdb99] MosaicViews v0.3.4
  [77ba4419] NaNMath v1.0.1
  [f09324ee] Netpbm v1.1.0
  [46757867] NetworkLayout v0.4.4
  [510215fc] Observables v0.5.4
  [6fe1bfb0] OffsetArrays v1.12.9
  [52e1d378] OpenEXR v0.3.2
  [bac558e1] OrderedCollections v1.4.1
  [90014a1f] PDMats v0.11.16
  [f57f5aa1] PNGFiles v0.3.17
  [19eb6ba3] Packing v0.5.0
  [5432bcbf] PaddedViews v0.5.11
  [69de0a69] Parsers v2.5.3
  [eebad327] PkgVersion v0.3.2
  [995b91a9] PlotUtils v1.3.4
  [647866c9] PolygonOps v0.1.2
  [21216c6a] Preferences v1.3.0
  [92933f4c] ProgressMeter v1.7.2
  [4b34888f] QOI v1.0.0
  [1fd47b50] QuadGK v2.7.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.3
  [189a3867] Reexport v1.2.2
  [05181044] RelocatableFolders v1.0.0
  [ae029012] Requires v1.3.0
  [79098fc4] Rmath v0.7.1
  [fdea26ae] SIMD v3.4.4
  [7b38b023] ScanByte v0.3.3
  [6c6a2e73] Scratch v1.1.1
  [efcf1570] Setfield v1.1.1
⌅ [65257c39] ShaderAbstractions v0.2.9
  [992d4aef] Showoff v1.0.3
  [73760f76] SignedDistanceFields v0.4.0
  [699a6c99] SimpleTraits v0.9.4
  [45858cf5] Sixel v0.1.2
  [66db9d55] SnoopPrecompile v1.0.3
  [a2af1166] SortingAlgorithms v1.1.0
  [276daf66] SpecialFunctions v2.1.7
  [c5dd0088] StableHashTraits v0.3.1
  [cae243ae] StackViews v0.1.1
  [90137ffa] StaticArrays v1.5.12
  [1e83bf80] StaticArraysCore v1.4.0
  [82ae8749] StatsAPI v1.5.0
  [2913bbd2] StatsBase v0.33.21
  [4c63d2b9] StatsFuns v1.1.1
  [09ab397b] StructArrays v0.6.14
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.10.0
  [62fd8b95] TensorCore v0.1.1
  [731e570b] TiffImages v0.6.3
  [3bb67fe8] TranscodingStreams v0.9.11
  [981d1d27] TriplotBase v0.1.0
  [9d95972d] TupleTools v1.3.0
  [1cfade01] UnicodeFun v0.4.1
  [efce3f68] WoodburyMatrices v0.5.5
  [6e34b625] Bzip2_jll v1.0.8+0
  [83423d85] Cairo_jll v1.16.1+1
  [5ae413db] EarCut_jll v2.2.4+0
  [2e619515] Expat_jll v2.4.8+0
  [b22a6f82] FFMPEG_jll v4.4.2+2
  [f5851436] FFTW_jll v3.3.10+0
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.10.4+0
  [559328eb] FriBidi_jll v1.0.10+0
  [0656b61e] GLFW_jll v3.3.8+0
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.74.0+2
  [3b182d85] Graphite2_jll v1.3.14+0
  [2e76f6c2] HarfBuzz_jll v2.8.1+1
  [905a6f67] Imath_jll v3.1.2+0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
  [aacddb02] JpegTurbo_jll v2.1.2+0
  [c1c5ebd0] LAME_jll v3.100.1+0
  [dd4b983a] LZO_jll v2.10.1+0
⌅ [e9f186c6] Libffi_jll v3.2.2+1
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7e76a0d4] Libglvnd_jll v1.6.0+0
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.16.1+2
  [4b2f31a3] Libmount_jll v2.35.0+0
  [38a345b3] Libuuid_jll v2.36.0+0
  [856f044c] MKL_jll v2022.2.0+0
  [e7412a2a] Ogg_jll v1.3.5+1
  [18a262bb] OpenEXR_jll v3.1.1+0
  [458c3c95] OpenSSL_jll v1.1.19+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [30392449] Pixman_jll v0.40.1+0
  [460c41e3] QhullMiniWrapper_jll v1.0.0+1
⌅ [784f63db] Qhull_jll v8.0.1001+0
  [f50d1b31] Rmath_jll v0.4.0+0
  [02c8fc9c] XML2_jll v2.10.3+0
  [aed1982a] XSLT_jll v1.1.34+0
  [4f6342f7] Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] Xorg_libXau_jll v1.0.9+4
  [935fb764] Xorg_libXcursor_jll v1.2.0+4
  [a3789734] Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [d091e8ba] Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] Xorg_libXi_jll v1.7.10+4
  [d1454406] Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] Xorg_libxcb_jll v1.13.0+3
  [c5fb5394] Xorg_xtrans_jll v1.4.0+3
  [9a68df92] isoband_jll v0.2.3+0
  [a4ae2306] libaom_jll v3.4.0+0
  [0ac62f75] libass_jll v0.15.1+0
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [b53b4c65] libpng_jll v1.6.38+0
  [075b6546] libsixel_jll v1.10.3+0
  [f27f6e37] libvorbis_jll v1.3.7+1
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [8bf52ea8] CRC32c
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL v0.6.3
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.9.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics v1.9.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.0.2+0
  [deac9b47] LibCURL_jll v7.84.0+0
  [29816b5a] LibSSH2_jll v1.10.2+0
  [c8ffd9c3] MbedTLS_jll v2.28.0+0
  [14a3606d] MozillaCACerts_jll v2022.10.11
  [4536629a] OpenBLAS_jll v0.3.21+0
  [05823500] OpenLibm_jll v0.8.1+0
  [efcefdf7] PCRE2_jll v10.42.0+0
  [bea87d4a] SuiteSparse_jll v5.10.1+0
  [83775a58] Zlib_jll v1.2.13+0
  [8e850b90] libblastrampoline_jll v5.2.0+0
  [8e850ede] nghttp2_jll v1.48.0+0
  [3f19e933] p7zip_jll v17.4.0+0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`

  ```
</details>

**Comment by hexaeder** [comment] 2023-01-30 09:27
Cannot reproduce (same Makie, GLMakie, GraphMakie and Graphs version). Same Julia, same CPU. Can you check if the problem also occurs for a basic `scatter` or `lines` plot? I suspect this happes further down the Makie stack. Maybe try to delete the compile cache and install GLMakie again?

copy pastable example:
```julia
using Pkg
pkg"activate --temp"
pkg"add GLMakie@0.8.1, GraphMakie, Graphs"
using GLMakie
using GraphMakie
using Graphs
g = complete_graph(10)
graphplot(g)
```
```
julia> versioninfo()
Julia Version 1.9.0-beta3
Commit 24204a73447 (2023-01-18 07:20 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  LD_LIBRARY_PATH = ~/.julia/conda/3/lib:
  JULIA_IMAGE_THREADS = 1
```

**Comment by anandijain** [comment] 2023-02-01 17:58
https://user-images.githubusercontent.com/33790004/216124533-7f9bd06c-4559-4075-9027-c61b64146ee1.mp4

its only when i click on the graph

**Comment by hexaeder** [comment] 2023-02-02 07:49
Interesting, I tried to reproduce again but I can click and zoom in the plot however I like. Is it also a problem with current GLMakie version 0.8.2?

Also, can you try
```julia
using Pkg
pkg"activate --temp"
pkg"add GLMakie@0.8.1, GraphMakie, Graphs"
using GLMakie, GraphMakie, Graphs
p = rand(Point2f, 10)
scatter(p)
lines!(p)
```

**Comment by anandijain** [comment] 2023-02-02 16:33
yeah same thing 
```julia 
[52225] signal (11.2): Segmentation fault: 11
in expression starting at none:0
_ZN9libunwind10CFI_ParserINS_17LocalAddressSpaceEE9decodeFDEERS1_mPNS2_8FDE_InfoEPNS2_8CIE_InfoE at /usr/lib/system/libunwind.dylib (unknown line)
Allocations: 37153196 (Pool: 37141327; Big: 11869); GC: 98
fish: Job 1, 'julia +beta --startup=no' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by gbaraldi** [comment] 2023-02-02 18:04
I've seen this before, this is an issue with the display backend. I can get this with just GLFW. 
https://github.com/MakieOrg/Makie.jl/issues/2517

**Comment by hdavid16** [comment] 2023-02-09 19:04
Closing as not a GraphMakie issue

**Closed by hdavid16** 2023-02-09 19:04 UTC
